### PR TITLE
Turning in assignment.

### PR DESCRIPTION
**Pull request by keawade**
No problems with the new submission workflow. The only thing that I was unsure about was the pull request. I think I did it correctly though.

### CODE REVIEW

**Comment by keawade** [comment]
A potential issue is that we can all see everyone's committed code.

Also, it seems that this submission workflow (In particular the testing) will only work if we stick to a pretty rigid curriculum. For example, my actual submission for this assignment won't work at all with the testing and would be a ridiculous amount of stuff to pile on with a pull.

**Comment by keawade** [comment]
Oh, it also seems I forgot to create the html file...

**Comment by keawade** [comment]
Fixed. Sorry about that.

Also, I like that the pull request is updated too. If I were working with a larger project and wanted to do that I should probably create a branch for the merge instead, yes?

**Comment by barberboy** [comment]
This looks great, Keith!

I'm glad you didn't run into any issues with the submission workflow. Your pull request is great.

I'm not worried about everyone seeing each others' code. Overall it's beneficial if people learn to read from and learn from other people's code, and I'll probably encourage people to comment and provide feedback on each others' pull requests. I know that it's possible that some students will use this to shortcut their learning process, but they are only hurting themselves in the process.

Regarding your Advanced Web Technologies submissions: I'm going to have you do the basic one first and create a pull request for that. Then create a separate branch (or branches) for the advanced ones, and submit separate pull requests for them.

The test files will always be in the "test" directory. When possible for your advanced exercises, I'd like you to add tests as appropriate for your projects, so we can use them as the foundation for exercises in the future.

**Pull request closed without merging**
