### PR TITLE
Finished up the test

### PR DESCRIPTION
**Pull request by crodeheaver**
I like the process, but I think the testing could be a bit more flexible. Or perhaps just let them know they needs to use your information specifically. I originally put my information in there and then realized it needed to be yours.

### CODE REVIEW

**Comment by barberboy** [comment]
Hmm, it's not intended to only work with only my information. It should work with your information just fine. The regex test for the message just verifies the overall form.

There _was_, however, a typo in the original assignment PDF—it was missing the word "major" after the <MAJOR> variable. So if your message string was based on that format, then that's probably why it failed.

Can you change this back to your information, commit, and push again?

**Comment by crodeheaver** [comment]
Yep, I see what happened. I first had all my issues with my info in there, so I put yours. Then I noticed the major in the error message so I added that. At that point, I'm pretty sure Mr. Purkeypile was catching on that I was doing something other than taking notes, so I pushed it before checking to see if it worked with my own information. It's updated and appears to be working

**Comment by barberboy** [comment]
There wasn't a test for it, but the assignment called for an `introduction.html` file as well as this one. Could you be sure to add that as well?

> Create an “introduction.html” file which includes “introduction.js”. View the Console in your browser’s Developer Tools to ensure that it is functioning correctly.

https://github.com/unioncollege-webtech/introduction#description

**Comment by crodeheaver** [comment]
I tend to find breaking up long lines to be less readable (assuming it's not so long it's overflowing anyways), but I'll try to remember to break them up for this class.

**Comment by barberboy** [comment]
This looks great, Cody!

You are welcome to your preferences, but you can see below how long lines can impede readability and hide small bugs (like my own in the original message format description). screen shot 2015-08-30 at 3 57 59 pm
https://github.com/crodeheaver/introduction/commit/0d9c92ed72980477c55b0d3b2cfb5492a7c39e6c

Also, if you plan on contributing to open source JavaScript projects, many — though certainly not all — of them have guideline for line length:

http://contribute.jquery.org/style-guide/js/#Spacing
https://github.com/airbnb/javascript#6.2
https://docs.npmjs.com/misc/coding-style
http://nodeguide.com/style.html#line-length
https://github.com/meteor/meteor/wiki/Meteor-Style-Guide#line-length

I don't expect or hope to change your mind, though! 

Thank you for abiding by this guideline for this class. Eventually we will adopt some JavaScript coding standards for the class that will be integrated into the tests as well.

**Pull request closed without merging**
