### PR TITLE
Introduction Submission

### PR DESCRIPTION
**Pull request by Malachi-M**
_This_ was Marvelous! 
Assignment files included.

### CODE REVIEW

**Comment by NathanBland** [comment]
Your build fails because you are missing the `()` around the letter `n` in the area around "major" in the sentence.

**Comment by barberboy** [comment]
Nathan is right, but I would consider this more a bug in the test than in your code. I think I'll change that...

**Comment by Malachi-M** [comment]
I wasn't sure if grammar was going to agree with the test.

**Comment by barberboy** [comment]
Tests are updated now on master to accept "a" or "an". Try fetching and merging it into your fork.

I think in the future I'll switch major and classStanding so it reads a bit better for you (us) alums.

**Comment by NathanBland** [comment]
if you don't already, you can add the upstream repo to your local version with
`git remote add upstream https://github.com/unioncollege-webtech/introduction.git`
Which you can then fetch/rebase.

**Comment by barberboy** [comment]
:+1:

**Pull request closed without merging**
